Update config/Kconfig to correct MDK MuC Version
MotorolaMobilityLLC/nuttx pull request #34
Opened 2017-07-15 02:29 UTC by Kmart777

Update config/Kconfig to correct MDK MuC version from STM32L476JG to STM32L476MG and so that menuconfig Board Selection Attributes point to desired user configuration options.

2017-07-15 05:10 UTC, Kmart777 commented
The push for arch: arm: Kconfig: Arrange HW selections to top of menuconfig GUI is optional.  I created 3rd party training material mirrored at https://drive.google.com/drive/folders/0B-w9A7ZbX8s4M3NNdzMySC13SXM that associates menuconfig attributes with their corresponding Kconfig files and line numbers.  Louis Begin is providing the .c and .h associations for each of the 3998 CONFIG_ variables.   I rearranged this section of code because I felt it would make a more intuitive user experience if HW selections were placed at the top of menuconfig.

2017-07-21 14:26 UTC, flowflow25 requested changes
As I recall we did NOT want to reorder this as it is intentionally in alphabetical order.

2017-07-21 14:28 UTC, flowflow25 commented on nuttx/arch/arm/src/stm32/Kconfig
> +endif
Where's the else?  This broke the use of STM32_ADC for anyone NOT using STM32_STM32L4

2017-07-21 14:31 UTC, flowflow25 reviewed
Did you build a firmware or two with these and make sure they still worked?

are you going to do another change to update all the sample projects to the correct chip?

2017-07-21 20:26 UTC, Kmart777 commented on nuttx/arch/arm/src/stm32/Kconfig
> +endif
I can't find a Kconfig example were ELSE is used, just multiple groupings of IF to ENDIF

2017-07-28 14:49 UTC, flowflow25 approved these changes

2017-07-28 16:44 UTC, Kmart777 commented
Replaced after consultation with flowflow25

2017-07-28 16:44 UTC, closed without merging